POST http://localhost:3001/api/workouts/
Content-Type: application/json
Authorization:

{
  "name": "Late night gym session",
  "description": "Great workout.. still feeling a bit sore..",
  "type": "Gym",
  "duration": 2000,
  "mood": "Sad"
}
